# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    expose:
      - 3306
    ports:
      - 3306:3306
  adminer:
    image: adminer
    links:
        - db
    restart: always
    ports:
      - 8080:8080